version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 9000:1972
      - 9001:52773
      - 9002:53773
    volumes:
      - ./:/irisrun/repo